// <auto-generated />
namespace YGOConsistencyCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ygo_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ygo_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202406042321009_ygo_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
